export const CREATE_VACCINE_BATCH_LOG_STARTED = 'CREATE_VACCINE_BATCH_LOG_STARTED';
export const CREATE_VACCINE_BATCH_LOG_COMPLETED = 'CREATE_VACCINE_BATCH_LOG_COMPLETED';

export const RETREIVE_VACCINE_BADGE_LOGS_STARTED = 'RETREIVE_VACCINE_BADGE_LOGS_STARTED';
export const RETREIVE_VACCINE_BADGE_LOGS_COMPLETED = 'RETREIVE_VACCINE_BADGE_LOGS_COMPLETED';
